name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install LLVM
      run: |
        sudo wget https://apt.llvm.org/llvm.sh
        sudo chmod +x llvm.sh
        sudo ./llvm.sh 20 all
        sudo update-alternatives --install /usr/bin/llvm-link llvm-link "$(command -v llvm-link-20)" 200
        sudo update-alternatives --set llvm-link "$(command -v llvm-link-20)"
        sudo update-alternatives --install /usr/bin/lli lli "$(command -v lli-20)" 200
        sudo update-alternatives --set lli "$(command -v lli-20)"
        sudo update-alternatives --install /usr/bin/clang clang "$(command -v clang-20)" 200
        sudo update-alternatives --set clang "$(command -v clang-20)"
        sudo apt-get install qemu-user gcc-aarch64-linux-gnu

    - name: Run tests
      run: cargo test --verbose
